services:
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  fake-gcs:
    image: fsouza/fake-gcs-server
    restart: always
    command: -scheme http -host 0.0.0.0 -port 4443 -public-host localhost:4443
    ports:
      - 4443:4443
    volumes:
      - fake-gcs-data:/storage

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: pass

volumes:
  mongo-data:
  fake-gcs-data:
