/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as SessionsSessionIdReviewRouteImport } from './routes/sessions.$sessionId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdReviewRoute = SessionsSessionIdReviewRouteImport.update({
  id: '/sessions/$sessionId/review',
  path: '/sessions/$sessionId/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$code': typeof SCodeRoute
  '/sessions/$sessionId/review': typeof SessionsSessionIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$code': typeof SCodeRoute
  '/sessions/$sessionId/review': typeof SessionsSessionIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s/$code': typeof SCodeRoute
  '/sessions/$sessionId/review': typeof SessionsSessionIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s/$code' | '/sessions/$sessionId/review'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$code' | '/sessions/$sessionId/review'
  id: '__root__' | '/' | '/s/$code' | '/sessions/$sessionId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SCodeRoute: typeof SCodeRoute
  SessionsSessionIdReviewRoute: typeof SessionsSessionIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/review': {
      id: '/sessions/$sessionId/review'
      path: '/sessions/$sessionId/review'
      fullPath: '/sessions/$sessionId/review'
      preLoaderRoute: typeof SessionsSessionIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SCodeRoute: SCodeRoute,
  SessionsSessionIdReviewRoute: SessionsSessionIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
